check branch before releasing on tag

diff --git a/.github/workflows/package.yml b/.github/workflows/package.yml
--- a/.github/workflows/package.yml
+++ b/.github/workflows/package.yml
@@ -14,9 +14,33 @@ env:
   CARGO_TERM_COLOR: always
 
 jobs:
+  check-branch:
+    runs-on: ubuntu-latest
+    outputs:
+      branch: ${{ steps.check_step.outputs.branch }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+
+      - name: Get current branch
+        id: check_step
+        run: |
+          raw=$(git branch -r --contains ${{ github.ref }})
+          branch=${raw##*/}
+          echo "branch=$branch" >> $GITHUB_OUTPUT
+          echo "Branch is $branch."
+          if [ "$branch" != "main" ]; then
+            echo "Error: Branch is not main"
+            exit 1
+          fi
+          echo "✓ Branch is main"
+
   build-linux:
     name: Build Linux (${{ matrix.target }})
     runs-on: ubuntu-22.04
+    needs: check-branch
     strategy:
       matrix:
         include:
@@ -102,6 +126,7 @@ jobs:
   build-macos:
     name: Build macOS (${{ matrix.target }})
     runs-on: macos-latest
+    needs: check-branch
     strategy:
       matrix:
         include:
